
  create table "public"."choreographers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
      );


alter table "public"."choreographers" enable row level security;


  create table "public"."dances" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "url" text,
    "video" text,
    "moves" text,
    "place_in_program" text,
    "notes" text,
    "difficulty" smallint,
    "swing_16" boolean
      );


alter table "public"."dances" enable row level security;


  create table "public"."dances_choreographers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "dance_id" bigint,
    "choreographer_id" bigint
      );


alter table "public"."dances_choreographers" enable row level security;


  create table "public"."programs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" date,
    "location" text
      );


alter table "public"."programs" enable row level security;


  create table "public"."programs_dances" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "order" smallint,
    "dance_id" bigint not null,
    "program_id" bigint
      );


alter table "public"."programs_dances" enable row level security;

CREATE UNIQUE INDEX choreographers_name_key ON public.choreographers USING btree (name);

CREATE UNIQUE INDEX choreographers_pkey ON public.choreographers USING btree (id);

CREATE UNIQUE INDEX "dancesPrograms_pkey" ON public.programs_dances USING btree (id);

CREATE UNIQUE INDEX dances_choreographers_pkey ON public.dances_choreographers USING btree (id);

CREATE UNIQUE INDEX dances_pkey ON public.dances USING btree (id);

CREATE INDEX idx_programs_dances_dance_id ON public.programs_dances USING btree (dance_id);

CREATE INDEX idx_programs_dances_program_id ON public.programs_dances USING btree (program_id);

CREATE UNIQUE INDEX programs_pkey ON public.programs USING btree (id);

alter table "public"."choreographers" add constraint "choreographers_pkey" PRIMARY KEY using index "choreographers_pkey";

alter table "public"."dances" add constraint "dances_pkey" PRIMARY KEY using index "dances_pkey";

alter table "public"."dances_choreographers" add constraint "dances_choreographers_pkey" PRIMARY KEY using index "dances_choreographers_pkey";

alter table "public"."programs" add constraint "programs_pkey" PRIMARY KEY using index "programs_pkey";

alter table "public"."programs_dances" add constraint "dancesPrograms_pkey" PRIMARY KEY using index "dancesPrograms_pkey";

alter table "public"."choreographers" add constraint "choreographers_name_key" UNIQUE using index "choreographers_name_key";

alter table "public"."dances_choreographers" add constraint "dances_choreographers_choreographer_id_fkey" FOREIGN KEY (choreographer_id) REFERENCES public.choreographers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dances_choreographers" validate constraint "dances_choreographers_choreographer_id_fkey";

alter table "public"."dances_choreographers" add constraint "dances_choreographers_dance_id_fkey" FOREIGN KEY (dance_id) REFERENCES public.dances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dances_choreographers" validate constraint "dances_choreographers_dance_id_fkey";

alter table "public"."programs_dances" add constraint "programs_dances_dance_id_fkey" FOREIGN KEY (dance_id) REFERENCES public.dances(id) ON DELETE CASCADE not valid;

alter table "public"."programs_dances" validate constraint "programs_dances_dance_id_fkey";

alter table "public"."programs_dances" add constraint "programs_dances_program_id_fkey" FOREIGN KEY (program_id) REFERENCES public.programs(id) ON DELETE CASCADE not valid;

alter table "public"."programs_dances" validate constraint "programs_dances_program_id_fkey";

grant delete on table "public"."choreographers" to "anon";

grant insert on table "public"."choreographers" to "anon";

grant references on table "public"."choreographers" to "anon";

grant select on table "public"."choreographers" to "anon";

grant trigger on table "public"."choreographers" to "anon";

grant truncate on table "public"."choreographers" to "anon";

grant update on table "public"."choreographers" to "anon";

grant delete on table "public"."choreographers" to "authenticated";

grant insert on table "public"."choreographers" to "authenticated";

grant references on table "public"."choreographers" to "authenticated";

grant select on table "public"."choreographers" to "authenticated";

grant trigger on table "public"."choreographers" to "authenticated";

grant truncate on table "public"."choreographers" to "authenticated";

grant update on table "public"."choreographers" to "authenticated";

grant delete on table "public"."choreographers" to "postgres";

grant insert on table "public"."choreographers" to "postgres";

grant references on table "public"."choreographers" to "postgres";

grant select on table "public"."choreographers" to "postgres";

grant trigger on table "public"."choreographers" to "postgres";

grant truncate on table "public"."choreographers" to "postgres";

grant update on table "public"."choreographers" to "postgres";

grant delete on table "public"."choreographers" to "service_role";

grant insert on table "public"."choreographers" to "service_role";

grant references on table "public"."choreographers" to "service_role";

grant select on table "public"."choreographers" to "service_role";

grant trigger on table "public"."choreographers" to "service_role";

grant truncate on table "public"."choreographers" to "service_role";

grant update on table "public"."choreographers" to "service_role";

grant delete on table "public"."dances" to "anon";

grant insert on table "public"."dances" to "anon";

grant references on table "public"."dances" to "anon";

grant select on table "public"."dances" to "anon";

grant trigger on table "public"."dances" to "anon";

grant truncate on table "public"."dances" to "anon";

grant update on table "public"."dances" to "anon";

grant delete on table "public"."dances" to "authenticated";

grant insert on table "public"."dances" to "authenticated";

grant references on table "public"."dances" to "authenticated";

grant select on table "public"."dances" to "authenticated";

grant trigger on table "public"."dances" to "authenticated";

grant truncate on table "public"."dances" to "authenticated";

grant update on table "public"."dances" to "authenticated";

grant delete on table "public"."dances" to "service_role";

grant insert on table "public"."dances" to "service_role";

grant references on table "public"."dances" to "service_role";

grant select on table "public"."dances" to "service_role";

grant trigger on table "public"."dances" to "service_role";

grant truncate on table "public"."dances" to "service_role";

grant update on table "public"."dances" to "service_role";

grant delete on table "public"."dances_choreographers" to "anon";

grant insert on table "public"."dances_choreographers" to "anon";

grant references on table "public"."dances_choreographers" to "anon";

grant select on table "public"."dances_choreographers" to "anon";

grant trigger on table "public"."dances_choreographers" to "anon";

grant truncate on table "public"."dances_choreographers" to "anon";

grant update on table "public"."dances_choreographers" to "anon";

grant delete on table "public"."dances_choreographers" to "authenticated";

grant insert on table "public"."dances_choreographers" to "authenticated";

grant references on table "public"."dances_choreographers" to "authenticated";

grant select on table "public"."dances_choreographers" to "authenticated";

grant trigger on table "public"."dances_choreographers" to "authenticated";

grant truncate on table "public"."dances_choreographers" to "authenticated";

grant update on table "public"."dances_choreographers" to "authenticated";

grant delete on table "public"."dances_choreographers" to "postgres";

grant insert on table "public"."dances_choreographers" to "postgres";

grant references on table "public"."dances_choreographers" to "postgres";

grant select on table "public"."dances_choreographers" to "postgres";

grant trigger on table "public"."dances_choreographers" to "postgres";

grant truncate on table "public"."dances_choreographers" to "postgres";

grant update on table "public"."dances_choreographers" to "postgres";

grant delete on table "public"."dances_choreographers" to "service_role";

grant insert on table "public"."dances_choreographers" to "service_role";

grant references on table "public"."dances_choreographers" to "service_role";

grant select on table "public"."dances_choreographers" to "service_role";

grant trigger on table "public"."dances_choreographers" to "service_role";

grant truncate on table "public"."dances_choreographers" to "service_role";

grant update on table "public"."dances_choreographers" to "service_role";

grant delete on table "public"."programs" to "anon";

grant insert on table "public"."programs" to "anon";

grant references on table "public"."programs" to "anon";

grant select on table "public"."programs" to "anon";

grant trigger on table "public"."programs" to "anon";

grant truncate on table "public"."programs" to "anon";

grant update on table "public"."programs" to "anon";

grant delete on table "public"."programs" to "authenticated";

grant insert on table "public"."programs" to "authenticated";

grant references on table "public"."programs" to "authenticated";

grant select on table "public"."programs" to "authenticated";

grant trigger on table "public"."programs" to "authenticated";

grant truncate on table "public"."programs" to "authenticated";

grant update on table "public"."programs" to "authenticated";

grant delete on table "public"."programs" to "service_role";

grant insert on table "public"."programs" to "service_role";

grant references on table "public"."programs" to "service_role";

grant select on table "public"."programs" to "service_role";

grant trigger on table "public"."programs" to "service_role";

grant truncate on table "public"."programs" to "service_role";

grant update on table "public"."programs" to "service_role";

grant delete on table "public"."programs_dances" to "anon";

grant insert on table "public"."programs_dances" to "anon";

grant references on table "public"."programs_dances" to "anon";

grant select on table "public"."programs_dances" to "anon";

grant trigger on table "public"."programs_dances" to "anon";

grant truncate on table "public"."programs_dances" to "anon";

grant update on table "public"."programs_dances" to "anon";

grant delete on table "public"."programs_dances" to "authenticated";

grant insert on table "public"."programs_dances" to "authenticated";

grant references on table "public"."programs_dances" to "authenticated";

grant select on table "public"."programs_dances" to "authenticated";

grant trigger on table "public"."programs_dances" to "authenticated";

grant truncate on table "public"."programs_dances" to "authenticated";

grant update on table "public"."programs_dances" to "authenticated";

grant delete on table "public"."programs_dances" to "service_role";

grant insert on table "public"."programs_dances" to "service_role";

grant references on table "public"."programs_dances" to "service_role";

grant select on table "public"."programs_dances" to "service_role";

grant trigger on table "public"."programs_dances" to "service_role";

grant truncate on table "public"."programs_dances" to "service_role";

grant update on table "public"."programs_dances" to "service_role";


  create policy "Allow full public access on choreographers"
  on "public"."choreographers"
  as permissive
  for all
  to authenticated, anon
using (true);



  create policy "Allow full public access on dances"
  on "public"."dances"
  as permissive
  for all
  to authenticated, anon
using (true);



  create policy "Allow full public access on dances_choreographers"
  on "public"."dances_choreographers"
  as permissive
  for all
  to authenticated, anon
using (true);



  create policy "Allow full public access on programs"
  on "public"."programs"
  as permissive
  for all
  to authenticated, anon
using (true);



  create policy "Allow full public access on dancesPrograms"
  on "public"."programs_dances"
  as permissive
  for all
  to authenticated, anon
using (true);



