-- dance_videos: one-to-many
create table "public"."dance_videos" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "dance_id" bigint not null,
  "url" text not null,
  "description" text,
  "user_id" uuid not null default auth.uid()
);

alter table "public"."dance_videos" enable row level security;

CREATE UNIQUE INDEX dance_videos_pkey ON public.dance_videos USING btree (id);
CREATE INDEX ON public.dance_videos (dance_id);
CREATE INDEX ON public.dance_videos (user_id);

alter table "public"."dance_videos" add constraint "dance_videos_pkey" PRIMARY KEY using index "dance_videos_pkey";

alter table "public"."dance_videos" add constraint "dance_videos_dance_id_fkey" FOREIGN KEY (dance_id) REFERENCES public.dances(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."dance_videos" validate constraint "dance_videos_dance_id_fkey";

alter table "public"."dance_videos" add constraint "dance_videos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."dance_videos" validate constraint "dance_videos_user_id_fkey";

-- Grants
grant delete on table "public"."dance_videos" to "anon";
grant insert on table "public"."dance_videos" to "anon";
grant references on table "public"."dance_videos" to "anon";
grant select on table "public"."dance_videos" to "anon";
grant trigger on table "public"."dance_videos" to "anon";
grant truncate on table "public"."dance_videos" to "anon";
grant update on table "public"."dance_videos" to "anon";

grant delete on table "public"."dance_videos" to "authenticated";
grant insert on table "public"."dance_videos" to "authenticated";
grant references on table "public"."dance_videos" to "authenticated";
grant select on table "public"."dance_videos" to "authenticated";
grant trigger on table "public"."dance_videos" to "authenticated";
grant truncate on table "public"."dance_videos" to "authenticated";
grant update on table "public"."dance_videos" to "authenticated";

grant delete on table "public"."dance_videos" to "postgres";
grant insert on table "public"."dance_videos" to "postgres";
grant references on table "public"."dance_videos" to "postgres";
grant select on table "public"."dance_videos" to "postgres";
grant trigger on table "public"."dance_videos" to "postgres";
grant truncate on table "public"."dance_videos" to "postgres";
grant update on table "public"."dance_videos" to "postgres";

grant delete on table "public"."dance_videos" to "service_role";
grant insert on table "public"."dance_videos" to "service_role";
grant references on table "public"."dance_videos" to "service_role";
grant select on table "public"."dance_videos" to "service_role";
grant trigger on table "public"."dance_videos" to "service_role";
grant truncate on table "public"."dance_videos" to "service_role";
grant update on table "public"."dance_videos" to "service_role";

-- RLS: owned by dance owner
create policy "user_access"
on "public"."dance_videos"
as permissive
for all
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

-- Migrate existing video data
insert into "public"."dance_videos" (dance_id, url, user_id)
select id, video, user_id
from "public"."dances"
where video is not null and video != '';

-- Drop old video column
alter table "public"."dances" drop column "video";
